Nano-Tech/Controllers/signupController.cs
using System;
using Nano_Tech.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Nano_Tech.Controllers;
using System.Web.Mvc;

namespace Nano_Tech.Controllers
{
    public class signupController : Controller
    {
        nanotechfinalEntities1 db = new nanotechfinalEntities1();
        // GET: signup
        public ActionResult signup()
        {   
            return View();
        }
        [HttpPost]
        public ActionResult adduser(user user1)
        {
            if (ModelState.IsValid)
            {
                user obj = new user();
                obj.username = user1.username;
                obj.userpass = user1.userpass;
                obj.usercontact = user1.usercontact;
                obj.useremail = user1.useremail;

                db.users.Add(obj);
                db.SaveChanges();
            }
            ModelState.Clear();
            return RedirectToAction("login","login");
        }
       
    }
    
}

Nano-Tech/Views/signup/signup.cshtml
@model Nano_Tech.Models.user
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" type="text/css" href="~/Content/loginstyle.css" />

    <title>User SIGNUP</title>
</head>
<body>
    <h2>User Signup</h2>
    @using (Html.BeginForm("adduser","signup", FormMethod.Post))
    {
        <div class="login">
            <form id="login" action="" method="post">


                @*<h5 style="color:red;">@ViewBag.msg</h5>*@
                <label for="uname"><b>Username</b></label>
                @*<input type="text" placeholder="Enter Username" name="uname" required>*@
                @Html.TextBoxFor(x => x.username, new { @class = "form-control", @placeholder = "User Name", @id = "Uname" })
                <span style="color:red">@Html.ValidationMessageFor(x => x.username)</span>

                <br />
                <label for="psw"><b>Password</b></label>
                @*<input type="password" placeholder="Enter Password" name="psw" required>*@

                @Html.PasswordFor(x => x.userpass, new { @class = "form-control", @placeholder = "Password", @id = "Pass" })
                <span style="color:red">@Html.ValidationMessageFor(x => x.userpass)</span>

                <br />

                <label for="psw"><b>Contact</b></label>
                @*<input type="password" placeholder="Enter Password" name="psw" required>*@

                @Html.TextBoxFor(x => x.usercontact, new { @class = "form-control", @placeholder = "Password", @id = "Uname" })
                <span style="color:red">@Html.ValidationMessageFor(x => x.usercontact)</span>

                <br />

                <label for="psw"><b>Email</b></label>
                @*<input type="password" placeholder="Enter Password" name="psw" required>*@

                @Html.TextBoxFor(x => x.useremail, new { @class = "form-control", @placeholder = "Password", @id = "Uname" })
                <span style="color:red">@Html.ValidationMessageFor(x => x.useremail)</span>

                <br />
                <div class="row">
                    <input type="submit" value="Signup" id="log" class="btn btn-success" />
                </div>


                <div class="form-group">
                    <p style="color:red">@ViewBag.error</p>
                </div>
                <br />
                <div>
                    @*<h5>Back to home</h5>*@
                    <a href='@Url.Action("Index", "Home")'>Back to home</a>
                </div>
            </form>
        </div>

    }
</body>
</html>
<script src="~/Scripts/jquery.validate-vsdoc.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
@section Scripts
    {


    @Scripts.Render("~/bundles/jqueryval")
}